# Generated by Django 4.1.4 on 2023-01-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_title_portfolio_full_name_portfolio_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projectParentSlug',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
    ]
