# Generated by Django 4.1.5 on 2023-01-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projects_projectparentslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolioslug',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
    ]
