# Generated by Django 4.1.5 on 2023-01-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_portfolioslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='projectParentSlug',
        ),
    ]
